# Generated by Django 5.1.15 on 2026-06-26 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=128)),
                ("description", models.TextField()),
                ("json_schema", models.JSONField(default=dict)),
                ("handler_key", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "skill",
            },
        ),
        migrations.CreateModel(
            name="SourcePlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("display_name", models.CharField(max_length=64)),
                ("adapter_key", models.CharField(max_length=64)),
                ("kind", models.CharField(max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "source_platform",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("system_prompt", models.TextField()),
                ("model", models.CharField(max_length=64)),
                (
                    "temperature",
                    models.DecimalField(decimal_places=2, default=0.7, max_digits=3),
                ),
                ("max_tool_rounds", models.SmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=False)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent",
            },
        ),
        migrations.CreateModel(
            name="AgentSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.SmallIntegerField(default=0)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_skills",
                        to="agents.agent",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_skills",
                        to="agents.skill",
                    ),
                ),
            ],
            options={
                "db_table": "agent_skill",
                "ordering": ["sort_order"],
                "unique_together": {("agent", "skill")},
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="agents",
                through="agents.AgentSkill",
                to="agents.skill",
            ),
        ),
        migrations.CreateModel(
            name="SourceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("value", models.CharField(max_length=255)),
                ("value_type", models.CharField(default="str", max_length=16)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="agents.sourceplatform",
                    ),
                ),
            ],
            options={
                "db_table": "source_config",
                "unique_together": {("platform", "key")},
            },
        ),
    ]
