# Generated by Django 5.1.15 on 2026-06-26 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=128)),
                ("kind", models.CharField(default="dcard", max_length=16)),
                ("is_readonly", models.BooleanField(default=True)),
                ("point_count", models.IntegerField(blank=True, null=True)),
                ("vector_size", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=16)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "memory_collection",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sid", models.CharField(max_length=32, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("message_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="agents.agent",
                    ),
                ),
                (
                    "end_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="accounts.enduser",
                    ),
                ),
            ],
            options={
                "db_table": "conversation",
                "ordering": ["-last_active_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=16)),
                ("content", models.TextField()),
                ("used_tools", models.JSONField(blank=True, null=True)),
                ("sources", models.JSONField(blank=True, null=True)),
                ("token_usage", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="memory.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "message",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["end_user"], name="conversatio_end_use_c2230f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["expires_at"], name="conversatio_expires_122fa6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"], name="message_convers_5aa82f_idx"
            ),
        ),
    ]
