# Generated by Django 5.1.15 on 2026-06-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("agents", "0001_initial"),
        ("memory", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["is_deleted", "-last_active_at", "-created_at"],
                name="conv_list_idx",
            ),
        ),
    ]
