# Generated by Django 5.1.15 on 2026-07-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memory", "0002_conversation_conv_list_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="chart",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
