# Generated by Django 5.1.15 on 2026-06-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("preferences", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("value", models.CharField(max_length=512)),
                ("value_type", models.CharField(default="str", max_length=16)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "end_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="accounts.enduser",
                    ),
                ),
            ],
            options={
                "db_table": "user_preference",
                "unique_together": {("end_user", "key")},
            },
        ),
    ]
